version: '3.8'

services:
  backend:
    build: ./coin_change_spring
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./coin_change_web
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge